#!/bin/bash

ip_address="192.168.1.1"  # Replace with your desired IP address
duration=$((60 * 60))     # 1 hour in seconds
disconnects=0

for ((i=0; i<duration; i++)); do
    if ! ping -c 1 -W 1 "$ip_address" >/dev/null 2>&1; then
        disconnects=$((disconnects + 1))
    fi
    sleep 1
done

echo "Number of disconnects in 1 hour: $disconnects"
